"$schema" = "https://starship.rs/config-schema.json"

format = """
$line_break \
$os\
$sudo\
$username\
$hostname\
$localip\
$shlvl\
$kubernetes\
$directory\
$git_commit\
$git_state\
$git_branch\
$git_status\
$git_metrics\
$package\
$docker_context\
$c\
$cpp\
$meson\
$cmake\
$zig\
$rust\
$golang\
$bun\
$nodejs\
$lua\
$kotlin\
$java\
$gradle\
$python\
$haskell\
$typst\
$fill \
$status\
$cmd_duration\
$jobs\
$shell\
$container\
$battery\
$time\
$line_break\
$character"""

palette = "flexoki"

[palettes.flexoki]
bg = "#100F0F"
bg-2 = "#1C1B1A"
ui = "#282726"
ui-2 = "#343331"
ui-3 = "#403E3C"
tx-3 = "#575653"
tx-2 = "#878580"
tx = "#CECDC3"
re = "#D14D41"
re-2 = "#AF3029"
or = "#DA702C"
or-2 = "#BC5215"
ye = "#D0A215"
ye-2 = "#AD8301"
gr = "#879A39"
gr-2 = "#66800B"
cy = "#3AA99F"
cy-2 = "#24837B"
bl = "#4385BE"
bl-2 = "#205EA6"
pu = "#8B7EC8"
pu-2 = "#5E409D"
ma = "#CE5D97"
ma-2 = "#A02F6F"

[os]
disabled = false
format = "[$symbol]($style)"
style = "bl-2"

[os.symbols]
Windows = " "
Ubuntu = "󰕈 "
Macos = " "
Linux = " "
Fedora = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Debian = " "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
NixOS = " "

[sudo]
disabled = false
format = "[sudo $symbol ]($style)"
symbol = " "
style = "bl-2"

[username]
format = "[$user]($style)"

[hostname]
format = "[[$ssh_symbol](cyan)$hostname ]($style)"
ssh_symbol = "@"
trim_at = "."

[shlvl]
disabled = false
format = "[$symbol$shlvl ]($style)"
symbol = ""

[directory]
format = "[$read_only]($read_only_style)[$path ]($style)"
style = "cyan"
truncation_length = 4
truncation_symbol = " "
read_only = "󰉐 "
repo_root_format = "[$before_root_path]($before_repo_root_style)[$read_only]($read_only_style)[󰊢 ](#F1502F)[$repo_root]($repo_root_style)[$path ]($style)"
repo_root_style = "or-2"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = "󰉍 "
"Music" = "󱍙 "
"Pictures" = " "

[git_commit]
format = '[ $tag(  $hash) ]($style)'
style = "green"
tag_disabled = false
tag_symbol = "󰓹 "

[git_state]
format = '\([$state( $progress_current/$progress_total) ]($style)\)'
style = "bold yellow"
rebase = " REBASING"
merge = " MERGING"
revert = "󰦛 REVERTING"
cherry_pick = " CHERRY-PICKING"
bisect = " BISECTING"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style)"
symbol = " "
style = "ma-2"
truncation_length = 24
truncation_symbol = " "

[git_status]
format = "[($all_status$ahead_behind) ]($style)"
style = "yellow"
ahead = '  ${count}'
behind = "  ${count}"
diverged = '  ${count}  ${count}'
conflicted = "[=](bold red)"
untracked = "?"
stashed = '\$'
modified = "!"
staged = "+"
renamed = "»"
deleted = "[](bold red)"
typechanged = ""

[git_metrics]
disabled = false

[package]
format = "[$symbol$version ]($style)"
symbol = "󰏓 "
style = "tx-2"

[docker_context]
format = "[$symbol($context) ]($style)"
symbol = " "
style = "tx-2"

[c]
format = "[$symbol($version) ]($style)"
symbol = " "
style = "149"

[cpp]
disabled = false
format = "[$symbol($version-$name) ]($style)"
symbol = " "
style = "149"

[meson]
format = "[$symbol$project ]($style)"
symbol = "󰋅 "
style = "blue"

[cmake]
format = "[$symbol($version) ]($style)"
symbol = " "
style = "blue"

[zig]
format = "[$symbol($version) ]($style)"
symbol = " "
style = "#f7a41d"

[rust]
symbol = " "
format = "[$symbol($version) ]($style)"
style = "or"

[golang]
symbol = " "
format = "[$symbol($version) ]($style)"
style = "blue"

[bun]
format = "[$symbol($version) ]($style)"
symbol = " "
style = "#fbf0df"

[nodejs]
format = "[$symbol($version) ]($style)"
symbol = " "
style = "green"

[lua]
format = "[$symbol($version) ]($style)"
symbol = "󰢱 "
style = "blue"

[kotlin]
format = "[$symbol($version) ]($style)"
symbol = "󱈙 "
style = "purple"

[java]
format = "[$symbol($version) ]($style)"
symbol = " "
style = "dimmed red"

[gradle]
format = "[$symbol($version )]($style)"
symbol = " "
style = "cyan"

[python]
format = "[[$symbol](#4B8BBE)($virtualenv )($version) ]($style)"
symbol = " "
style = "#FFD43B"

[haskell]
format = "[$symbol($version )]($style)"
symbol = " "
style = "purple"

[fill]
symbol = "─"
style = "tx-3"

[status]
format = "[$symbol$status ]($style)"
disabled = false
symbol = " "
not_executable_symbol = " "
not_found_symbol = " "
sigint_symbol = "󰜺 "
signal_symbol = " "
style = "bold red"
map_symbol = true
pipestatus = true

[cmd_duration]
format = "[$duration ]($style)"

[jobs]
format = "[$symbol$number ]($style)"
symbol = " "
style = "blue"

[battery]
format = "[$symbol$percentage ]($style)"
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "
empty_symbol = " "
unknown_symbol = "󱟨 "

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 30
style = "yellow"

[[battery.display]]
threshold = 50
style = "tx"

[[battery.display]]
threshold = 80
style = "tx-2"

[time]
format = "[$time ]($style)"
disabled = false
time_format = "%R"
style = "tx-2"

[character]
format = " $symbol "
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
vimcmd_symbol = "[](bold green)"
vimcmd_replace_one_symbol = "[](bold purple)"
vimcmd_replace_symbol = "[](bold purple)"
vimcmd_visual_symbol = "[](bold yellow)"

